// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(Db))]
    [Migration("20240202083935_01_TableNewValueNotificationAdded")]
    partial class _01_TableNewValueNotificationAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Database.Tables.TableAccessToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("GuiltyUntilUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("TblUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TblUserId");

                    b.ToTable("AccessToken");
                });

            modelBuilder.Entity("Database.Tables.TableCompany", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CompanyType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("Database.Tables.TableCompanyGlobalConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AdditionalConfiguration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ConfigVersion")
                        .HasColumnType("bigint");

                    b.Property<int>("GlobalConfigType")
                        .HasColumnType("int");

                    b.Property<long>("TblCompanyId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TblCompanyId");

                    b.ToTable("CompanyGlobalConfig");
                });

            modelBuilder.Entity("Database.Tables.TableDataconverter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CodeSnippet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Displayname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dataconverter");
                });

            modelBuilder.Entity("Database.Tables.TableDevice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceHardwareId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeviceIdiom")
                        .HasColumnType("int");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAppRunning")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastDateTimeUtcOnline")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatingSystemVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Plattform")
                        .HasColumnType("int");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScreenResolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TblUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TblUserId");

                    b.ToTable("Device");
                });

            modelBuilder.Entity("Database.Tables.TableFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AdditionalData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Bytes")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("File");
                });

            modelBuilder.Entity("Database.Tables.TableGateway", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AdditionalConfiguration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdditionalProperties")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TblCompanyId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TblCompanyId");

                    b.ToTable("Gateway");
                });

            modelBuilder.Entity("Database.Tables.TableIotDevice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AdditionalConfiguration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdditionalProperties")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MeasurementInterval")
                        .HasColumnType("int");

                    b.Property<int>("Plattform")
                        .HasColumnType("int");

                    b.Property<bool>("SuccessfullyRegisteredInThirdPartySystem")
                        .HasColumnType("bit");

                    b.Property<long?>("TblCompanyGlobalConfigId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblDataconverterId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblGatewayId")
                        .HasColumnType("bigint");

                    b.Property<int>("TransmissionInterval")
                        .HasColumnType("int");

                    b.Property<int>("TransmissionType")
                        .HasColumnType("int");

                    b.Property<int>("Upstream")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TblCompanyGlobalConfigId");

                    b.HasIndex("TblDataconverterId");

                    b.HasIndex("TblGatewayId");

                    b.ToTable("IotDevice");
                });

            modelBuilder.Entity("Database.Tables.TableMeasurementDefinition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AdditionalConfiguration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdditionalProperties")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DownstreamType")
                        .HasColumnType("int");

                    b.Property<int>("MeasurementInterval")
                        .HasColumnType("int");

                    b.Property<long>("TblIotDeviceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblLatestMeasurementResultId")
                        .HasColumnType("bigint");

                    b.Property<int>("ValueType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TblIotDeviceId");

                    b.ToTable("MeasurementDefinition");
                });

            modelBuilder.Entity("Database.Tables.TableMeasurementDefinitionTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("TblDataconverterId")
                        .HasColumnType("bigint");

                    b.Property<int>("ValueType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TblDataconverterId");

                    b.ToTable("MeasurementDefinitionTemplate");
                });

            modelBuilder.Entity("Database.Tables.TableMeasurementDefinitionToProjectAssignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("TblMeasurementDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblProjctId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TblMeasurementDefinitionId");

                    b.HasIndex("TblProjctId");

                    b.ToTable("MeasurementDefinitionToProjectAssignment");
                });

            modelBuilder.Entity("Database.Tables.TableMeasurementResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AdditionalConfiguration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdditionalProperties")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Point>("SpatialPoint")
                        .IsRequired()
                        .HasColumnType("geography");

                    b.Property<long>("TblMeasurementDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("ValueType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TblMeasurementDefinitionId");

                    b.ToTable("MeasurementResult", t =>
                        {
                            t.HasTrigger("measurementresult_insert_trigger");
                        });
                });

            modelBuilder.Entity("Database.Tables.TableNewValueNotification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AdditionalConfiguration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("DataVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<int>("NewValueNotificationType")
                        .HasColumnType("int");

                    b.Property<long>("TblMeasurementDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<long>("TblUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TblMeasurementDefinitionId");

                    b.HasIndex("TblUserId");

                    b.ToTable("NewValueNotification");
                });

            modelBuilder.Entity("Database.Tables.TablePermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AdditionalConfiguration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdditionalProperties")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TblCompanyId")
                        .HasColumnType("bigint");

                    b.Property<long>("TblUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("UserRight")
                        .HasColumnType("int");

                    b.Property<int>("UserRole")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TblCompanyId");

                    b.HasIndex("TblUserId");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("Database.Tables.TableProject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AdditionalProperties")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<bool>("Published")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("TblCompanyId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TblCompanyId");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("Database.Tables.TableSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Key")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Setting");
                });

            modelBuilder.Entity("Database.Tables.TableUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AgbVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfirmationToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("JwtToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Locked")
                        .HasColumnType("bit");

                    b.Property<bool>("LoginConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("LoginName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PushTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Setting10MinPush")
                        .HasColumnType("bit");

                    b.Property<long?>("TblUserImageId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TblUserImageId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Database.Tables.TableAccessToken", b =>
                {
                    b.HasOne("Database.Tables.TableUser", "TblUser")
                        .WithMany("TblAccessToken")
                        .HasForeignKey("TblUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TblUser");
                });

            modelBuilder.Entity("Database.Tables.TableCompany", b =>
                {
                    b.OwnsOne("Database.Common.DbInformation", "Information", b1 =>
                        {
                            b1.Property<long>("TableCompanyId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("UpdatedDate")
                                .HasColumnType("datetime2");

                            b1.HasKey("TableCompanyId");

                            b1.ToTable("Company");

                            b1.WithOwner()
                                .HasForeignKey("TableCompanyId");
                        });

                    b.Navigation("Information")
                        .IsRequired();
                });

            modelBuilder.Entity("Database.Tables.TableCompanyGlobalConfig", b =>
                {
                    b.HasOne("Database.Tables.TableCompany", "TblCompany")
                        .WithMany("TblCompanyGlobalConfigurations")
                        .HasForeignKey("TblCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Database.Common.DbInformation", "Information", b1 =>
                        {
                            b1.Property<long>("TableCompanyGlobalConfigId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("UpdatedDate")
                                .HasColumnType("datetime2");

                            b1.HasKey("TableCompanyGlobalConfigId");

                            b1.ToTable("CompanyGlobalConfig");

                            b1.WithOwner()
                                .HasForeignKey("TableCompanyGlobalConfigId");
                        });

                    b.Navigation("Information")
                        .IsRequired();

                    b.Navigation("TblCompany");
                });

            modelBuilder.Entity("Database.Tables.TableDevice", b =>
                {
                    b.HasOne("Database.Tables.TableUser", "TblUser")
                        .WithMany("TblDevices")
                        .HasForeignKey("TblUserId");

                    b.Navigation("TblUser");
                });

            modelBuilder.Entity("Database.Tables.TableGateway", b =>
                {
                    b.HasOne("Database.Tables.TableCompany", "TblCompany")
                        .WithMany("TblGateways")
                        .HasForeignKey("TblCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Database.Common.DbDeviceCommon", "DeviceCommon", b1 =>
                        {
                            b1.Property<long>("TableGatewayId")
                                .HasColumnType("bigint");

                            b1.Property<long>("ConfigversionDevice")
                                .HasColumnType("bigint");

                            b1.Property<long>("ConfigversionService")
                                .HasColumnType("bigint");

                            b1.Property<string>("FirmwareversionDevice")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FirmwareversionService")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("LastOfflineTime")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("LastOnlineTime")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Secret")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("State")
                                .HasColumnType("int");

                            b1.HasKey("TableGatewayId");

                            b1.ToTable("Gateway");

                            b1.WithOwner()
                                .HasForeignKey("TableGatewayId");
                        });

                    b.OwnsOne("Database.Common.DbInformation", "Information", b1 =>
                        {
                            b1.Property<long>("TableGatewayId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("UpdatedDate")
                                .HasColumnType("datetime2");

                            b1.HasKey("TableGatewayId");

                            b1.ToTable("Gateway");

                            b1.WithOwner()
                                .HasForeignKey("TableGatewayId");
                        });

                    b.OwnsOne("Database.Common.DbPosition", "Position", b1 =>
                        {
                            b1.Property<long>("TableGatewayId")
                                .HasColumnType("bigint");

                            b1.Property<double>("Altitude")
                                .HasColumnType("float");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");

                            b1.Property<double>("Precision")
                                .HasColumnType("float");

                            b1.Property<int>("Source")
                                .HasColumnType("int");

                            b1.Property<DateTime>("TimeStamp")
                                .HasColumnType("datetime2");

                            b1.HasKey("TableGatewayId");

                            b1.ToTable("Gateway");

                            b1.WithOwner()
                                .HasForeignKey("TableGatewayId");
                        });

                    b.Navigation("DeviceCommon")
                        .IsRequired();

                    b.Navigation("Information")
                        .IsRequired();

                    b.Navigation("Position")
                        .IsRequired();

                    b.Navigation("TblCompany");
                });

            modelBuilder.Entity("Database.Tables.TableIotDevice", b =>
                {
                    b.HasOne("Database.Tables.TableCompanyGlobalConfig", "TblCompanyGlobalConfigs")
                        .WithMany("TblIotDevice")
                        .HasForeignKey("TblCompanyGlobalConfigId");

                    b.HasOne("Database.Tables.TableDataconverter", "TblDataconverter")
                        .WithMany()
                        .HasForeignKey("TblDataconverterId");

                    b.HasOne("Database.Tables.TableGateway", "TblGateway")
                        .WithMany("TblIotDevices")
                        .HasForeignKey("TblGatewayId");

                    b.OwnsOne("Database.Common.DbDeviceCommon", "DeviceCommon", b1 =>
                        {
                            b1.Property<long>("TableIotDeviceId")
                                .HasColumnType("bigint");

                            b1.Property<long>("ConfigversionDevice")
                                .HasColumnType("bigint");

                            b1.Property<long>("ConfigversionService")
                                .HasColumnType("bigint");

                            b1.Property<string>("FirmwareversionDevice")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FirmwareversionService")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("LastOfflineTime")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("LastOnlineTime")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Secret")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("State")
                                .HasColumnType("int");

                            b1.HasKey("TableIotDeviceId");

                            b1.ToTable("IotDevice");

                            b1.WithOwner()
                                .HasForeignKey("TableIotDeviceId");
                        });

                    b.OwnsOne("Database.Common.DbPosition", "FallbackPosition", b1 =>
                        {
                            b1.Property<long>("TableIotDeviceId")
                                .HasColumnType("bigint");

                            b1.Property<double>("Altitude")
                                .HasColumnType("float");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");

                            b1.Property<double>("Precision")
                                .HasColumnType("float");

                            b1.Property<int>("Source")
                                .HasColumnType("int");

                            b1.Property<DateTime>("TimeStamp")
                                .HasColumnType("datetime2");

                            b1.HasKey("TableIotDeviceId");

                            b1.ToTable("IotDevice");

                            b1.WithOwner()
                                .HasForeignKey("TableIotDeviceId");
                        });

                    b.OwnsOne("Database.Common.DbInformation", "Information", b1 =>
                        {
                            b1.Property<long>("TableIotDeviceId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("UpdatedDate")
                                .HasColumnType("datetime2");

                            b1.HasKey("TableIotDeviceId");

                            b1.ToTable("IotDevice");

                            b1.WithOwner()
                                .HasForeignKey("TableIotDeviceId");
                        });

                    b.Navigation("DeviceCommon")
                        .IsRequired();

                    b.Navigation("FallbackPosition")
                        .IsRequired();

                    b.Navigation("Information")
                        .IsRequired();

                    b.Navigation("TblCompanyGlobalConfigs");

                    b.Navigation("TblDataconverter");

                    b.Navigation("TblGateway");
                });

            modelBuilder.Entity("Database.Tables.TableMeasurementDefinition", b =>
                {
                    b.HasOne("Database.Tables.TableIotDevice", "TblIoTDevice")
                        .WithMany("TblMeasurementDefinitions")
                        .HasForeignKey("TblIotDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Database.Common.DbInformation", "Information", b1 =>
                        {
                            b1.Property<long>("TableMeasurementDefinitionId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("UpdatedDate")
                                .HasColumnType("datetime2");

                            b1.HasKey("TableMeasurementDefinitionId");

                            b1.ToTable("MeasurementDefinition");

                            b1.WithOwner()
                                .HasForeignKey("TableMeasurementDefinitionId");
                        });

                    b.Navigation("Information")
                        .IsRequired();

                    b.Navigation("TblIoTDevice");
                });

            modelBuilder.Entity("Database.Tables.TableMeasurementDefinitionTemplate", b =>
                {
                    b.HasOne("Database.Tables.TableDataconverter", "TblDataconverter")
                        .WithMany("Templates")
                        .HasForeignKey("TblDataconverterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Database.Common.DbInformation", "Information", b1 =>
                        {
                            b1.Property<long>("TableMeasurementDefinitionTemplateId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("UpdatedDate")
                                .HasColumnType("datetime2");

                            b1.HasKey("TableMeasurementDefinitionTemplateId");

                            b1.ToTable("MeasurementDefinitionTemplate");

                            b1.WithOwner()
                                .HasForeignKey("TableMeasurementDefinitionTemplateId");
                        });

                    b.Navigation("Information")
                        .IsRequired();

                    b.Navigation("TblDataconverter");
                });

            modelBuilder.Entity("Database.Tables.TableMeasurementDefinitionToProjectAssignment", b =>
                {
                    b.HasOne("Database.Tables.TableMeasurementDefinition", "TblMeasurmentDefinitions")
                        .WithMany("TblMeasurementDefinitionToProjectAssignments")
                        .HasForeignKey("TblMeasurementDefinitionId");

                    b.HasOne("Database.Tables.TableProject", "TblProjcts")
                        .WithMany("TblMeasurementDefinitionToProjectAssignments")
                        .HasForeignKey("TblProjctId");

                    b.Navigation("TblMeasurmentDefinitions");

                    b.Navigation("TblProjcts");
                });

            modelBuilder.Entity("Database.Tables.TableMeasurementResult", b =>
                {
                    b.HasOne("Database.Tables.TableMeasurementDefinition", "TblMeasurementDefinition")
                        .WithMany("TblMeasurements")
                        .HasForeignKey("TblMeasurementDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Database.Common.DbValue", "Value", b1 =>
                        {
                            b1.Property<long>("TableMeasurementResultId")
                                .HasColumnType("bigint");

                            b1.Property<byte[]>("Binary")
                                .HasColumnType("varbinary(max)");

                            b1.Property<bool?>("Bit")
                                .HasColumnType("bit");

                            b1.Property<double?>("Number")
                                .HasColumnType("float");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TableMeasurementResultId");

                            b1.ToTable("MeasurementResult");

                            b1.WithOwner()
                                .HasForeignKey("TableMeasurementResultId");
                        });

                    b.OwnsOne("Database.Common.DbPosition", "Location", b1 =>
                        {
                            b1.Property<long>("TableMeasurementResultId")
                                .HasColumnType("bigint");

                            b1.Property<double>("Altitude")
                                .HasColumnType("float");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");

                            b1.Property<double>("Precision")
                                .HasColumnType("float");

                            b1.Property<int>("Source")
                                .HasColumnType("int");

                            b1.Property<DateTime>("TimeStamp")
                                .HasColumnType("datetime2");

                            b1.HasKey("TableMeasurementResultId");

                            b1.ToTable("MeasurementResult");

                            b1.WithOwner()
                                .HasForeignKey("TableMeasurementResultId");
                        });

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("TblMeasurementDefinition");

                    b.Navigation("Value")
                        .IsRequired();
                });

            modelBuilder.Entity("Database.Tables.TableNewValueNotification", b =>
                {
                    b.HasOne("Database.Tables.TableMeasurementDefinition", "TblMeasurementDefinition")
                        .WithMany()
                        .HasForeignKey("TblMeasurementDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Tables.TableUser", "TblUser")
                        .WithMany()
                        .HasForeignKey("TblUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TblMeasurementDefinition");

                    b.Navigation("TblUser");
                });

            modelBuilder.Entity("Database.Tables.TablePermission", b =>
                {
                    b.HasOne("Database.Tables.TableCompany", "TblCompany")
                        .WithMany("TblPermissions")
                        .HasForeignKey("TblCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Tables.TableUser", "TblUser")
                        .WithMany("TblPermissions")
                        .HasForeignKey("TblUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TblCompany");

                    b.Navigation("TblUser");
                });

            modelBuilder.Entity("Database.Tables.TableProject", b =>
                {
                    b.HasOne("Database.Tables.TableCompany", "TblCompany")
                        .WithMany("TblProjects")
                        .HasForeignKey("TblCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Database.Common.DbInformation", "Information", b1 =>
                        {
                            b1.Property<long>("TableProjectId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("UpdatedDate")
                                .HasColumnType("datetime2");

                            b1.HasKey("TableProjectId");

                            b1.ToTable("Project");

                            b1.WithOwner()
                                .HasForeignKey("TableProjectId");
                        });

                    b.Navigation("Information")
                        .IsRequired();

                    b.Navigation("TblCompany");
                });

            modelBuilder.Entity("Database.Tables.TableUser", b =>
                {
                    b.HasOne("Database.Tables.TableFile", "TblUserImage")
                        .WithMany("TblUserImages")
                        .HasForeignKey("TblUserImageId");

                    b.Navigation("TblUserImage");
                });

            modelBuilder.Entity("Database.Tables.TableCompany", b =>
                {
                    b.Navigation("TblCompanyGlobalConfigurations");

                    b.Navigation("TblGateways");

                    b.Navigation("TblPermissions");

                    b.Navigation("TblProjects");
                });

            modelBuilder.Entity("Database.Tables.TableCompanyGlobalConfig", b =>
                {
                    b.Navigation("TblIotDevice");
                });

            modelBuilder.Entity("Database.Tables.TableDataconverter", b =>
                {
                    b.Navigation("Templates");
                });

            modelBuilder.Entity("Database.Tables.TableFile", b =>
                {
                    b.Navigation("TblUserImages");
                });

            modelBuilder.Entity("Database.Tables.TableGateway", b =>
                {
                    b.Navigation("TblIotDevices");
                });

            modelBuilder.Entity("Database.Tables.TableIotDevice", b =>
                {
                    b.Navigation("TblMeasurementDefinitions");
                });

            modelBuilder.Entity("Database.Tables.TableMeasurementDefinition", b =>
                {
                    b.Navigation("TblMeasurementDefinitionToProjectAssignments");

                    b.Navigation("TblMeasurements");
                });

            modelBuilder.Entity("Database.Tables.TableProject", b =>
                {
                    b.Navigation("TblMeasurementDefinitionToProjectAssignments");
                });

            modelBuilder.Entity("Database.Tables.TableUser", b =>
                {
                    b.Navigation("TblAccessToken");

                    b.Navigation("TblDevices");

                    b.Navigation("TblPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
