//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResCommon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResCommon() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResCommon", typeof(ResCommon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück.
        /// </summary>
        public static string CmdBack {
            get {
                return ResourceManager.GetString("CmdBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string CmdCancel {
            get {
                return ResourceManager.GetString("CmdCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string CmdHome {
            get {
                return ResourceManager.GetString("CmdHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string CmdInfo {
            get {
                return ResourceManager.GetString("CmdInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string CmdLogin {
            get {
                return ResourceManager.GetString("CmdLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mehr.
        /// </summary>
        public static string CmdMore {
            get {
                return ResourceManager.GetString("CmdMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mehr Infos.
        /// </summary>
        public static string CmdMoreToolTip {
            get {
                return ResourceManager.GetString("CmdMoreToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein.
        /// </summary>
        public static string CmdNo {
            get {
                return ResourceManager.GetString("CmdNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string CmdOk {
            get {
                return ResourceManager.GetString("CmdOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        public static string CmdSettings {
            get {
                return ResourceManager.GetString("CmdSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ich.
        /// </summary>
        public static string CmdUser {
            get {
                return ResourceManager.GetString("CmdUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        public static string CmdYes {
            get {
                return ResourceManager.GetString("CmdYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbunden.
        /// </summary>
        public static string EnumConnConnected {
            get {
                return ResourceManager.GetString("EnumConnConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbindungsaufbau.
        /// </summary>
        public static string EnumConnConnecting {
            get {
                return ResourceManager.GetString("EnumConnConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schließe Verbindung.
        /// </summary>
        public static string EnumConnDisconnecting {
            get {
                return ResourceManager.GetString("EnumConnDisconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string EnumConnDisonnected {
            get {
                return ResourceManager.GetString("EnumConnDisonnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser.
        /// </summary>
        public static string EnumDeviceTypeBrowser {
            get {
                return ResourceManager.GetString("EnumDeviceTypeBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Computer.
        /// </summary>
        public static string EnumDeviceTypePc {
            get {
                return ResourceManager.GetString("EnumDeviceTypePc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System-Administrator.
        /// </summary>
        public static string EnumUserRoleSysAdmin {
            get {
                return ResourceManager.GetString("EnumUserRoleSysAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Infos!.
        /// </summary>
        public static string MsgHeaderInfos {
            get {
                return ResourceManager.GetString("MsgHeaderInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info! Dieser Command wird nicht selektiert!.
        /// </summary>
        public static string MsgInfo {
            get {
                return ResourceManager.GetString("MsgInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Account wurde gesperrt. Sie werden jetzt abgemeldet!.
        /// </summary>
        public static string MsgLocked {
            get {
                return ResourceManager.GetString("MsgLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht möglich da keine Verbindung zum Server besteht.
        /// </summary>
        public static string MsgNotConnected {
            get {
                return ResourceManager.GetString("MsgNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht gespeicherte Daten gehen verloren!
        ///Wollen Sie fortfahren?.
        /// </summary>
        public static string MsgNotSaved {
            get {
                return ResourceManager.GetString("MsgNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string MsgTitleEmail {
            get {
                return ResourceManager.GetString("MsgTitleEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        public static string MsgTitleError {
            get {
                return ResourceManager.GetString("MsgTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MsgTitleHeaderInfos {
            get {
                return ResourceManager.GetString("MsgTitleHeaderInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MsgTitleInfo {
            get {
                return ResourceManager.GetString("MsgTitleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account-Sperre.
        /// </summary>
        public static string MsgTitleLocked {
            get {
                return ResourceManager.GetString("MsgTitleLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbindung.
        /// </summary>
        public static string MsgTitleNotConnected {
            get {
                return ResourceManager.GetString("MsgTitleNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achtung.
        /// </summary>
        public static string MsgTitleNotSaved {
            get {
                return ResourceManager.GetString("MsgTitleNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Version.
        /// </summary>
        public static string MsgTitleUpdateAvailable {
            get {
                return ResourceManager.GetString("MsgTitleUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Version.
        /// </summary>
        public static string MsgTitleUpdateMandatory {
            get {
                return ResourceManager.GetString("MsgTitleUpdateMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine aktualisiert Version ({0}) der App ist vorhanden..
        /// </summary>
        public static string MsgUpdateAvailable {
            get {
                return ResourceManager.GetString("MsgUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine aktualisiert Version ({0}) der App ist vorhanden. Bitte aktualisieren Sie die App. App wird jetzt beendet!.
        /// </summary>
        public static string MsgUpdateMandatory {
            get {
                return ResourceManager.GetString("MsgUpdateMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine gültige E-Mail.
        /// </summary>
        public static string ValNoEmail {
            get {
                return ResourceManager.GetString("ValNoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darf nicht leer sein!.
        /// </summary>
        public static string ValNotEmpty {
            get {
                return ResourceManager.GetString("ValNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leerzeichen nicht erlaubt.
        /// </summary>
        public static string ValNoWhitespace {
            get {
                return ResourceManager.GetString("ValNoWhitespace", resourceCulture);
            }
        }
    }
}
