//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewUser {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewUser() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResViewUser", typeof(ResViewUser).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort.
        /// </summary>
        public static string CmdChangePassword {
            get {
                return ResourceManager.GetString("CmdChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten.
        /// </summary>
        public static string CmdEdit {
            get {
                return ResourceManager.GetString("CmdEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string CmdLogout {
            get {
                return ResourceManager.GetString("CmdLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zugriffstoken.
        /// </summary>
        public static string LblAccessToken {
            get {
                return ResourceManager.GetString("LblAccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma.
        /// </summary>
        public static string LblCompany {
            get {
                return ResourceManager.GetString("LblCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Id:.
        /// </summary>
        public static string LblDeviceId {
            get {
                return ResourceManager.GetString("LblDeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hersteller.
        /// </summary>
        public static string LblDeviceManufacturer {
            get {
                return ResourceManager.GetString("LblDeviceManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string LblDeviceModel {
            get {
                return ResourceManager.GetString("LblDeviceModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerätename.
        /// </summary>
        public static string LblDeviceName {
            get {
                return ResourceManager.GetString("LblDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geräte.
        /// </summary>
        public static string LblDevices {
            get {
                return ResourceManager.GetString("LblDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geräte des Benutzers.
        /// </summary>
        public static string LblDevicesSubTitle {
            get {
                return ResourceManager.GetString("LblDevicesSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geräte.
        /// </summary>
        public static string LblDevicesTitle {
            get {
                return ResourceManager.GetString("LblDevicesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzerstammdaten bearbeiten.
        /// </summary>
        public static string LblEditUser {
            get {
                return ResourceManager.GetString("LblEditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste.
        /// </summary>
        public static string LblListTitle {
            get {
                return ResourceManager.GetString("LblListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string LblLog {
            get {
                return ResourceManager.GetString("LblLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuellen Benutzer abmelden.
        /// </summary>
        public static string LblLogout {
            get {
                return ResourceManager.GetString("LblLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort ändern.
        /// </summary>
        public static string LblPassword {
            get {
                return ResourceManager.GetString("LblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berechtigungen in Organisationen.
        /// </summary>
        public static string LblPermissionsSubTitle {
            get {
                return ResourceManager.GetString("LblPermissionsSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berechtigungen.
        /// </summary>
        public static string LblPermissionsTitle {
            get {
                return ResourceManager.GetString("LblPermissionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meine Daten, Berechtigungen, App-Geräte und Zugriffstoken.
        /// </summary>
        public static string LblSubTitle {
            get {
                return ResourceManager.GetString("LblSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer.
        /// </summary>
        public static string LblTitle {
            get {
                return ResourceManager.GetString("LblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        public static string LblToken {
            get {
                return ResourceManager.GetString("LblToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekannt.
        /// </summary>
        public static string LblUnknown {
            get {
                return ResourceManager.GetString("LblUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id:.
        /// </summary>
        public static string LblUserId {
            get {
                return ResourceManager.GetString("LblUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechte.
        /// </summary>
        public static string LblUserRight {
            get {
                return ResourceManager.GetString("LblUserRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolle.
        /// </summary>
        public static string LblUserRole {
            get {
                return ResourceManager.GetString("LblUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string LblUserRoleAdmin {
            get {
                return ResourceManager.GetString("LblUserRoleAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fahrer.
        /// </summary>
        public static string LblUserRoleDriver {
            get {
                return ResourceManager.GetString("LblUserRoleDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gültig bis.
        /// </summary>
        public static string LblValidTill {
            get {
                return ResourceManager.GetString("LblValidTill", resourceCulture);
            }
        }
    }
}
