//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewLogin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewLogin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResViewLogin", typeof(ResViewLogin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bei der Arbeit ....
        /// </summary>
        public static string BsyLogin {
            get {
                return ResourceManager.GetString("BsyLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weiter.
        /// </summary>
        public static string CmdContinue {
            get {
                return ResourceManager.GetString("CmdContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort neu.
        /// </summary>
        public static string CmdForgotPassword {
            get {
                return ResourceManager.GetString("CmdForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string CmdLogin {
            get {
                return ResourceManager.GetString("CmdLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email senden.
        /// </summary>
        public static string CmdResendAccessLink {
            get {
                return ResourceManager.GetString("CmdResendAccessLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestehenden Login oder neue E-Mail.
        /// </summary>
        public static string EntryPlaceholderLoginName {
            get {
                return ResourceManager.GetString("EntryPlaceholderLoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login (E-Mail).
        /// </summary>
        public static string EntryTitleLoginName {
            get {
                return ResourceManager.GetString("EntryTitleLoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort.
        /// </summary>
        public static string EntryTitlePassword {
            get {
                return ResourceManager.GetString("EntryTitlePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mit einem bestehenden Account anmelden.
        /// </summary>
        public static string LblSubTitle {
            get {
                return ResourceManager.GetString("LblSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LblTitle {
            get {
                return ResourceManager.GetString("LblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestätigungsemail wurde versandt..
        /// </summary>
        public static string MsgConfirmationSent {
            get {
                return ResourceManager.GetString("MsgConfirmationSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es gibt keinen Account mit dieser Email. Bitte wenden Sie sich an den Administrator Ihrer Firma!.
        /// </summary>
        public static string MsgNewUser {
            get {
                return ResourceManager.GetString("MsgNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine E-Mail zum Zurücksetzen des Passworts wurde gesendet..
        /// </summary>
        public static string MsgResetSent {
            get {
                return ResourceManager.GetString("MsgResetSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim vesenden des E-Mails ist aufgetreten..
        /// </summary>
        public static string MsgSendError {
            get {
                return ResourceManager.GetString("MsgSendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string MsgTitleNewUser {
            get {
                return ResourceManager.GetString("MsgTitleNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort.
        /// </summary>
        public static string MsgTitleWrongPassword {
            get {
                return ResourceManager.GetString("MsgTitleWrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Login-Name wurde nicht bestätigt. Bitte prüfen Sie Ihren Posteingang..
        /// </summary>
        public static string MsgUserNotValidated {
            get {
                return ResourceManager.GetString("MsgUserNotValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültiges Passwort.
        /// </summary>
        public static string MsgWrongPassword {
            get {
                return ResourceManager.GetString("MsgWrongPassword", resourceCulture);
            }
        }
    }
}
