//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewSettingsPush {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewSettingsPush() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResViewSettingsPush", typeof(ResViewSettingsPush).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Settings.
        /// </summary>
        public static string CmdOpenSettings {
            get {
                return ResourceManager.GetString("CmdOpenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestPush senden.
        /// </summary>
        public static string CmdSendPush {
            get {
                return ResourceManager.GetString("CmdSendPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push aktiv:.
        /// </summary>
        public static string LblPushActive {
            get {
                return ResourceManager.GetString("LblPushActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pushes deaktiviert.
        /// </summary>
        public static string LblPushInactive {
            get {
                return ResourceManager.GetString("LblPushInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Tasks:.
        /// </summary>
        public static string LblPushTasks {
            get {
                return ResourceManager.GetString("LblPushTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persönliche Push Einstellungen verwalten.
        /// </summary>
        public static string LblSubTitle {
            get {
                return ResourceManager.GetString("LblSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle 10 Minuten Push.
        /// </summary>
        public static string LblTenMinPush {
            get {
                return ResourceManager.GetString("LblTenMinPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push.
        /// </summary>
        public static string LblTitle {
            get {
                return ResourceManager.GetString("LblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topics:.
        /// </summary>
        public static string LblTopics {
            get {
                return ResourceManager.GetString("LblTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Einstellung konnte nicht übernommen werden!.
        /// </summary>
        public static string MsgSettingsNotSaved {
            get {
                return ResourceManager.GetString("MsgSettingsNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        public static string MsgTitleSettingsNotSaved {
            get {
                return ResourceManager.GetString("MsgTitleSettingsNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MsgTitleTopicNotSaved {
            get {
                return ResourceManager.GetString("MsgTitleTopicNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Topic konnte nicht im DC gespeichert werden..
        /// </summary>
        public static string MsgTopicNotSaved {
            get {
                return ResourceManager.GetString("MsgTopicNotSaved", resourceCulture);
            }
        }
    }
}
